### PR TITLE
initial improvements for test outcomes on Windows - improves #441 (tests on …

### LINKED ISSUE #441: Some unit tests fail on Windows
We need someone with a Windows machine who can fix and test this issue. Help would be greatly appreciated.

### PR DESCRIPTION
**Pull request by paulk-asert**
…Windows)

Thanks for contributing.

- [ X] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

What was changed? BOM handling is now catered for.

## Testing

Did you add a unit test? The current unit tests now pass on Windows. I haven't included adding:

os:
  - windows
  - linux
  - osx

to travis CI config in this PR but let me know if you want me to add it.

### CODE REVIEW

**Comment by paulk-asert** [comment]
Note: this is a minimal solution - it assumes you are happy with specifying the charset for the troublesome cases (which is certainly a valid stance to take) and it currently only handles the UTF-8 case. If you want to not have to specify the charset and have it work for e.g. UTF-16 cases, you need something more like what Groovy does in CharsetToolkit:

https://github.com/apache/groovy/blob/master/src/main/java/groovy/util/CharsetToolkit.java#L387

My thinking was that you could start with the minimal solution and always add the more complicated version if there was demand.

File: core/src/main/java/tech/tablesaw/io/Source.java [hunk 1]
```diff
@@ -19,6 +20,11 @@
     protected final Reader reader;
     protected final InputStream inputStream;
     protected final Charset charset;
+    private final Charset UTF8 = Charset.forName("UTF-8");
+
+    public Source(String filename) {
```
Comment (benmccann) [inline core/src/main/java/tech/tablesaw/io/Source.java]: I'd rather not add so many new constructors to `Source`. If we want to make it easier to call I'd probably do it by adding new methods to `CsvReadOptions`. E.g. where we have `CsvReadOptions.builderFromFile` maybe add a new one with a charset parameter

File: core/src/main/java/tech/tablesaw/io/Source.java [hunk 2]
```diff
@@ -84,12 +106,37 @@ public Reader createReader(byte[] cachedBytes) throws IOException {
...
+    /**
+     *  Returns a new Reader on the underlying source object.
+     */
+    private Reader getReader(InputStream raw) throws IOException {
+        // we want to remove the BOM windows adds from a file if the encoding is UTF-8
+        // in other cases we depend on the charsets
+        InputStream in = new BufferedInputStream(raw);
+        if (UTF8.name().equalsIgnoreCase(charset.name())) {
+            in.mark(3);
+            boolean hasBOM = true;
```
Comment (benmccann) [inline core/src/main/java/tech/tablesaw/io/Source.java]: We use univocity-parsers, which is supposed to do BOM handling for us. It's not clear to me why this would be required. Can we either change our test or file a bug with univocity so that we don't have to do any special logic here?

Comment (paulk-asert) [reply core/src/main/java/tech/tablesaw/io/Source.java]: Okay, I didn't know about BOM handling within univocity-parsers. It seems like you need to explicitly make use of the BomInput class for univocity-parsers to do what is needed. I'll see if I can rework the PR based around that.

**Comment by paulk-asert** [comment]
I moved the less controversial changes into this PR and will create a separate PR for the BOM changes. So this now fixes two of the tests plus does some minor refactoring (moved what looked like a stray misplaced comment and removed some minor duplication in a couple of constructors).

File: core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReadOptions.java [hunk 3]
```diff
@@ -174,6 +173,10 @@ public Builder lineEnding(String lineEnding) {
             return this;
         }
 
+        public Builder platformLineEnding() {
+            return lineEnding(System.getProperty("line.separator"));
```
Comment (benmccann) [inline core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReadOptions.java]: I'd suggest `System.lineSeparator()` over `System.getProperty("line.separator")`

File: core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReadOptions.java [hunk 4]
```diff
@@ -174,6 +173,10 @@ public Builder lineEnding(String lineEnding) {
             return this;
         }
 
+        public Builder platformLineEnding() {
```
Comment (benmccann) [inline core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReadOptions.java]: How about calling this `systemLineEnding` for greater consistency with the Java API?

Comment (paulk-asert) [reply core/src/main/java/tech/tablesaw/io/fixed/FixedWidthReadOptions.java]: Done
