### PR TITLE
Provide more helpful error messages when a column cannot be found on Row

### LINKED ISSUE #617: Create Better Column Not Found Error Message for Row
Ran into this today while using the library.

`row.getLong("colDoesNotExist")` throws an NPE. We should create a better error message. Possibly create a custom ColumnNotFoundException (unchecked) and use it project wide.

Current error message:

```
Exception in thread "main" java.lang.NullPointerException
	at tech.tablesaw.api.Row.getLong(Row.java:153)
	at com.ryancerf.tgo.steps.CreateInvoicesStep.createInvoices(CreateInvoicesStep.java:23)
	at com.ryancerf.tgo.Main.main(Main.java:40)
```

This error also occurs when the column name exists on the table, but the type is wrong. It would be nice if we searched the possible column names and gave the user the hint that they probably got the wrong `row.get` method.

If no one has grabbed this I should have time to work on it in a few days.

### PR DESCRIPTION
**Pull request by ryancerf**
Thanks for contributing.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

Fixes #617

New Error Msgs look like:

For missing column:
```
Column col2 is not present in table myTable
```

For using wrong type.
```
Column col1 is of type LOCAL_DATE and cannot be cast to LOCAL_TIME. Use the method for LOCAL_DATE.
```

## Testing

Yes. Added tests.

### CODE REVIEW

File: core/src/main/java/tech/tablesaw/api/Row.java [hunk 1]
```diff
@@ -4,39 +4,90 @@
...
 import tech.tablesaw.columns.Column;
 import tech.tablesaw.table.TableSlice;
 
 public class Row implements Iterator<Row> {
 
+  /**
+   * Wrap Map of column name to Column map and provide helpful error messages to the user when a
+   * column name cannot be found.
+   */
+  private class ColumnMap<T> {
```
Comment (benmccann) [inline core/src/main/java/tech/tablesaw/api/Row.java]: make this static?

Comment (ryancerf) [reply core/src/main/java/tech/tablesaw/api/Row.java]: In order to provide the context in the error messages ColumnMap needs access to the table and list of columns. If we wanted to make it static we could create all the ColumnMaps in Row's constructor, but it is more concise the way it is. Happy to change it if you like.

As far as inner classes go I think they are fine as long as they are private and no object outside the containing class can hold a reference to the inner class.
