### PR TITLE
Fix #441 allowing to build project with Windows

### LINKED ISSUE #441: Some unit tests fail on Windows
We need someone with a Windows machine who can fix and test this issue. Help would be greatly appreciated.

### PR DESCRIPTION
**Pull request by lujop**
Thanks for contributing.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

Fixes issue #441 allowing to build project with Windows and with systems that don't has en-US as default locale

Changes made:
- Changing hardcoded line separator for `System.lineSeparator()'. Except in HTML writer because Jsoup seems to use always Unix line separator.
- Putting all surefire args in one line because two didn't work and system locale was used.
- Changed mocked URLs because Inet URLs were used as if they were valid local filesystem urls.
- Disabled BOM test. I think that test being failing is correct, at least in systems that don't use UTF-8. I haven't seen any management of BOM in the `tablesaw` code, and `univocity` seems to manage BOM but only when a `File` is passed and not a `Reader` as `tablesaw` uses.

### CODE REVIEW

File: core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java [hunk 1]
```diff
@@ -81,10 +85,14 @@ public void toSqlStringNumbering() {
             .build();
 
     String expectd =
-        "SELECT\n"
-            + "RANK() OVER w1 AS myRank\n"
-            + "FROM myTable\n"
-            + "Window w1 AS (\n"
+        "SELECT"
+            + System.lineSeparator()
```
Comment (benmccann) [inline core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java:89]: this seems a little hard to read to me. Can we put each `System.lineSeparator()` on the end of the line instead of putting it on a new line?

Comment (lujop) [reply core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java:89]: Yes, I don't like also. But it was done by the formatter plugin that is configurated in maven. 
In fact, it separated a lot of lines from the way I initially leave them.
Is it used?

Comment (lwhite1) [reply core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java:89]: it wouldn't hurt to use a static import so you could just write ```lineSeparator()```. Even that is too verbose, but you can't fight Java names.

Comment (benmccann) [reply core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java:89]: You could make it even shorter by assigning it to a constant at the top of the file like `NEW_LINE`

One day we'll have Java 13's triple quotes and this will all be cleaner, but it's probably too early for that since Java 11 is the last LTS unless maybe we can just run the tests on Java 13, but compile with Java 11

Comment (lujop) [reply core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java:89]: Yes I can use static import to reduce size, but about the new line I don't like it too.
But is what made the formatter plugin. I suppose that it sees a string concatenation that is two big and wants every concatenation in its new line.

What do you want me to do?
Only static import?
Reformat by hand trying to use fewer lines and ignoring formatter plugin? In that case are there any formatting rules that I must follow?

Comment (benmccann) [reply core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java:89]: You shouldn't format by hand. I'm not sure how the other options would look, but they're worth experimenting with

Comment (lujop) [reply core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java:89]: Ok, then I should do just use a static import on all line separators? Any other thing it's needed to be changed?

Comment (benmccann) [reply core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java:89]: I would say we should try it and see how it looks

File: core/src/test/java/tech/tablesaw/io/DataFrameReaderTest.java [hunk 2]
```diff
@@ -50,8 +50,7 @@ public void csv() throws IOException {
   @Test
   public void readUrlWithExtension() throws Exception {
     URL url =
-        mockUrlHelper(
-            "http://something.other.com/file.csv", ImmutableList.of("region", "canada", "us"));
+        mockUrlHelper("something.other.com/file.csv", ImmutableList.of("region", "canada", "us"));
```
Comment (benmccann) [inline core/src/test/java/tech/tablesaw/io/DataFrameReaderTest.java:53]: It looks weird to me that `http://` is missing. I didn't understand the explanation for why it had to be changed. Is there a fix we can make to `mockUrlHelper` or something that will allow `http://` to be used?

File: core/src/test/java/tech/tablesaw/io/csv/UnicodeBomHandlingTest.java [hunk 3]
```diff
@@ -22,6 +23,7 @@
   }
 
   @Test
+  @Disabled
```
Comment (benmccann) [inline core/src/test/java/tech/tablesaw/io/csv/UnicodeBomHandlingTest.java:26]: Maybe can we change it to read a File instead so that we at least ensure that case is working?

Comment (lujop) [reply core/src/test/java/tech/tablesaw/io/csv/UnicodeBomHandlingTest.java:26]: Maybe I'm wrong but I really think that the problem is not the test.
It's actually `tablesaw` code that fails to manage BOM in non Unicode environments.

Because if there isn't any management code in `tablesaw` code itself the management that does `univocity`, to my understanding,  only works if we call the parser using a File.
But actual code never uses that method and always preprocess the File itself and passes a reader.

To correct that I think that it will be better to create an issue and manage it in another PR because it will require some refactors on file processing and cache system used.

If my diagnostic is correct I think that disabling the test is better because it lies.

Comment (benmccann) [reply core/src/test/java/tech/tablesaw/io/csv/UnicodeBomHandlingTest.java:26]: Ah, ok. I forgot we didn't call the univocity file method even when the input is a file. That makes sense then

File: core/src/test/java/tech/tablesaw/io/DataFrameReaderTest.java (hunk 2 above)
Comment (lujop) [reply core/src/test/java/tech/tablesaw/io/DataFrameReaderTest.java]: Changed the mockUrl to be able to use urls

File: core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java (hunk 1 above)
Comment (lujop) [reply core/src/test/java/tech/tablesaw/analytic/AnalyticQueryTest.java]: At the end, I use a LINE_END constant that I've seen that was used in some places.

File: jsplot/src/test/java/tech/tablesaw/components/LayoutTest.java [hunk 4]
```diff
@@ -55,58 +58,62 @@ public void testAutosize() {
...
       assertEquals(
-          "var layout = {\n"
-              + //
-              "    autosize: true,\n"
-              + //
-              "\n\n"
-              + //
-              "};\n",
+          "var layout = {"
+              + lineSeparator()
```
Comment (benmccann) [inline jsplot/src/test/java/tech/tablesaw/components/LayoutTest.java:62]: this one should be `LINE_END` to match the others and then you no longer need the static `import`

**Comment by benmccann** [comment]
can you rebase this PR? thanks!

**Comment by benmccann** [comment]
Can you try adding Windows to the CI so that we avoid regressing? It should just be changing the line below:

https://github.com/jtablesaw/tablesaw/blob/56508ba0ba6e180b80e1809538a586689c1b963d/.github/workflows/ci.yml#L19

**Comment by lujop** [comment]
> Can you try adding Windows to the CI so that we avoid regressing? It should just be changing the line below:
> 
> https://github.com/jtablesaw/tablesaw/blob/56508ba0ba6e180b80e1809538a586689c1b963d/.github/workflows/ci.yml#L19

Done

File: .github/workflows/ci.yml [hunk 5]
```diff
@@ -17,7 +17,7 @@ jobs:
         java-version: [1.8, 11, 15]
         # Tests seem to be failing on Windows
```
Comment (benmccann) [inline .github/workflows/ci.yml:18]: can you remove this line and the next line?

Comment (lujop) [reply .github/workflows/ci.yml]: OMG, I didn't see it.
Done

**Comment by lujop** [comment]
I've seen that build on windows crashes on JAva 15, 
Can I change for 16 that is the lastest now and retry?

**Comment by benmccann** [comment]
Hmm, that's weird. But sure, go ahead and try changing 15 to 16
